### ISSUE TITLE
faker.random.hexaDecimal doesn't work on latest version (4.1.0)

### ISSUE THREAD

**Issue by ninesalt** [Marak/faker.js#673]
Getting error `faker.random.hexaDecimal is not a function`. Will try to figure out the source of the problem in faker source code.

**Comment by Marak** [comment]
Try `master`

**Comment by richsong** [comment]
Can confirm - it doesn't work.
`{
"statusCode": 500,
"error": "Internal Server Error",
"message": "faker.random.hexaDecimal is not a function"
}`

**Comment by gimyboya** [comment]
this issue is still relevant the `random` module doesn't contain the function `hexaDecimal`

![image](https://user-images.githubusercontent.com/14952013/44520387-4be6f300-a702-11e8-9f4a-ed708f347f27.png)

thus the error '_faker.random.hexaDecimal is not a function`

**Comment by richsong** [comment]
You could use this for the time being:
```
  generateRandomHexaDecimal() {
    return `#${Math.random().toString(16).slice(2, 8).toUpperCase()}`;
  }
```
